# For documentation, see https://golangci-lint.run/usage/configuration/

linters:
  enable:
    - dupl
    - exportloopref
    - gci
    - goconst
    - gocritic
    - gofmt
    - gofumpt
    - perfsprint
    - prealloc
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign

linters-settings:
  gocritic:
    disabled-checks:
      - appendAssign
      - unlambda
    settings:
      ifElseChain:
        minThreshold: 4