name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:

  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: stable
      - uses: golangci/golangci-lint-action@v9
        with:
          version: v2.6

  test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        go-version:
          - "oldstable"
          - "stable"
          - "" # Fall back to using go-version-file below; see https://github.com/actions/setup-go/issues/450#issuecomment-3620402646.

    steps:

    - name: Checkout
      uses: actions/checkout@v6

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ matrix.go-version }}
        go-version-file: go.mod # Only used when go-version is empty.

    - name: Install dbus
      run: sudo apt-get update && sudo apt-get install dbus dbus-x11

    - name: Build
      run: go build -race -v ./...

    - name: Test
      run: go test -race -v ./...

  codespell:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v6
    - uses: codespell-project/actions-codespell@v2

  lima:
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        template: [freebsd-15]
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v6

    - uses: lima-vm/lima-actions/setup@v1
      id: lima-actions-setup

    - uses: actions/cache@v5
      with:
        path: ~/.cache/lima
        key: lima-${{ steps.lima-actions-setup.outputs.version }}-${{ matrix.template }}

    - name: Install xorriso (needed by lima)
      run: sudo apt-get install -qqy xorriso

    - name: Start VM
      # --plain is set to disable file sharing, port forwarding, built-in containerd, etc. for faster start up
      #
      # CPUs: min(4, host CPU cores)
      # RAM:  min(4 GiB, half of host memory)
      # Disk: 100 GiB
      run: limactl start --plain --name=default template:${{ matrix.template }}

    - name: Setup VM
      run: |
        set -eux
        limactl cp -r . default:/tmp/godbus
        lima sudo chmod a-x /usr/bin/fortune
        lima sudo pkg install -y go dbus
        lima sudo /usr/local/etc/rc.d/dbus onestart

    - name: VM info
      run: |
        set -eux
        lima uname -a
        lima go version

    - name: Run tests
      run: |
        lima sh -c 'eval $(dbus-launch --sh-syntax) && cd /tmp/godbus && go test -v ./...'

  all-done:
    runs-on: ubuntu-latest
    needs:
      - lima
      - lint
      - test
      - codespell
    steps:
    - run: echo "All jobs completed"
